/*
 * defines.h
 *
 *  Created on: Nov 29, 2019
 *      Author: grzegorz
 */

#ifndef INC_DEFINES_H_
#define INC_DEFINES_H_

#define SCPI_MANUFACTURER_STRING_LENGTH 65
#define SCPI_DEVICE_STRING_LENGTH 11
#define SCPI_SERIALNUMBER_STRING_LENGTH 65
#define SCPI_SOFTWAREVERSION_STRING_LENGTH 65
#define PASSWORD_LENGTH 65
#define PASSWORD "ETH6C20MUX"

#endif /* INC_DEFINES_H_ */
